### ISSUE TITLE
jenkins2 pipeline error at npm run test-single-run -- --browsers PhantomJS'

### ISSUE THREAD

**Issue by kuops** [g0t4/solitaire-systemjs-course#5]
when i runing a jenkins job 
```
stage 'CI'
node {

    git branch: 'jenkins2-course', 
        url: 'https://github.com/g0t4/solitaire-systemjs-course'

    // pull dependencies from npm
    // on windows use: bat 'npm install'
    env.PATH = "/usr/local/node/bin/:/usr/local/phantomjs/bin/:${env.PATH}"
    sh 'npm install'

    // stash code & dependencies to expedite subsequent testing
    // and ensure same code & dependencies are used throughout the pipeline
    // stash is a temporary archive
    stash name: 'everything', 
          excludes: 'test-results/**', 
          includes: '**'
    
    // test with PhantomJS for "fast" "generic" results
    // on windows use: bat 'npm run test-single-run -- --browsers PhantomJS'
    sh 'npm run test-single-run -- --browsers PhantomJS'
    
    // archive karma test results (karma is configured to export junit xml files)
    step([$class: 'JUnitResultArchiver', 
          testResults: 'test-results/**/test-results.xml'])
          
}

def notify(status){
    emailext (
      to: "wesmdemos@gmail.com",
      subject: "${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
      body: """<p>${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
        <p>Check console output at <a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a></p>""",
    )
}
```
have a error at `npm run test-single-run -- --browsers PhantomJS`
```
[solitaire pipeline] Running shell script
+ npm run test-single-run -- --browsers PhantomJS

> solitaire@0.0.0 test-single-run /var/jenkins_home/workspace/solitaire pipeline
> karma start karma.conf.js --single-run "--browsers" "PhantomJS"

[33m07 06 2017 02:57:38.861:WARN [watcher]: [39mPattern "/var/jenkins_home/workspace/solitaire pipeline/app/bower_components/angular/angular.js" does not match any file.
[33m07 06 2017 02:57:38.864:WARN [watcher]: [39mPattern "/var/jenkins_home/workspace/solitaire pipeline/app/bower_components/angular-route/angular-route.js" does not match any file.
[33m07 06 2017 02:57:38.865:WARN [watcher]: [39mPattern "/var/jenkins_home/workspace/solitaire pipeline/app/bower_components/angular-mocks/angular-mocks.js" does not match any file.
[33m07 06 2017 02:57:38.865:WARN [watcher]: [39mPattern "/var/jenkins_home/workspace/solitaire pipeline/app/bower_components/underscore/underscore.js" does not match any file.
[33m07 06 2017 02:57:38.892:WARN [karma]: [39mPort 9876 in use
[33m07 06 2017 02:57:38.893:WARN [karma]: [39mPort 9877 in use
[32m07 06 2017 02:57:38.893:INFO [karma]: [39mKarma v0.13.22 server started at http://localhost:9878/
[32m07 06 2017 02:57:38.901:INFO [launcher]: [39mStarting browser PhantomJS
[32m07 06 2017 02:57:39.099:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: [39mConnected on socket 4pHDy2Y0mbXAky7VAAAA with id 40750653
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  ReferenceError: Can't find variable: angular
  at /var/jenkins_home/workspace/solitaire pipeline/app/klondike/board.js:4


PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  ReferenceError: Can't find variable: angular
  at /var/jenkins_home/workspace/solitaire pipeline/app/klondike/game.js:4


[31m07 06 2017 02:57:39.178:ERROR [karma]: [39mTypeError: Cannot read property '40750653' of null
    at JUnitReporter.onBrowserComplete (/var/jenkins_home/workspace/solitaire pipeline/node_modules/karma-junit-reporter/index.js:102:23)
    at Server.<anonymous> (/var/jenkins_home/workspace/solitaire pipeline/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:111:20)
    at Server.emit (events.js:191:7)
    at Browser.onComplete (/var/jenkins_home/workspace/solitaire pipeline/node_modules/karma/lib/browser.js:142:13)
    at Socket.<anonymous> (/var/jenkins_home/workspace/solitaire pipeline/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:111:20)
    at Socket.emit (events.js:191:7)
    at /var/jenkins_home/workspace/solitaire pipeline/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

npm ERR! Linux 3.10.0-514.el7.x86_64
npm ERR! argv "/usr/local/node-v6.11.0-linux-x64/bin/node" "/usr/local/node/bin/npm" "run" "test-single-run" "--" "--browsers" "PhantomJS"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! solitaire@0.0.0 test-single-run: `karma start karma.conf.js --single-run "--browsers" "PhantomJS"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the solitaire@0.0.0 test-single-run script 'karma start karma.conf.js --single-run "--browsers" "PhantomJS"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the solitaire package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     karma start karma.conf.js --single-run "--browsers" "PhantomJS"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs solitaire
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls solitaire
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/jenkins_home/workspace/solitaire pipeline/npm-debug.log
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
```
the system is centos7  
the jenkins runing on docker
the npm and phantomjs is installed 
```
root@jenkins:/var/jenkins_home/workspace/solitaire pipeline# phantomjs -v
2.1.1
root@jenkins:/var/jenkins_home/workspace/solitaire pipeline# npm -v      
3.10.10
```

**Comment by Heucles** [comment]
Hey @opspy I think that I had a similar scenario to the one that you described, here is how I solved it.

1. Fork the repository
2. Move the bower dependencies to npm (not required but will prevent you from several warnings)
3. Fix the path over the karma.conf.js file  (now it should refer to the node_modules instead of bower_components)
4. Fix the path over the app/index.html (now it should refer to the node_modules instead of bower_components)
5. Remove the bower install from your package.json and also from your pipeline

If you want, feel free to check out my fork:
https://github.com/Heucles/solitaire-systemjs-course

PS: make sure to refer to the correct branch while building the new version of the pipeline
